cozy/cozy-bar

- config/webpack.config.base.js
- package.json
- src/index.js
This PR ensure we build a real UMD module, and exposes it at root level under the namespace `cozy` (i.e. `window.cozy.client`)
> Build UMD modules in root['cozy']

- src/lib/i18n.js
`console.warning` is not a function, as my browser would say.
> [fix] Fix a call to console.warn

- src/index.js
This PR disable DOM events on unexisting `drawer` panel in mobile flavor
> Fix issue with unexisting drawer on mobile

- src/components/NavigationItem.svelte
- src/components/Storage.svelte
- src/lib/config.js
- src/lib/stack.js
- src/locales/en.json
Basically I just copied and pasted what existed before for disk usage. I tried to do both with a one shot request but couldn't get this thing to work with an object instead of a single string.
Also, i didn't copied the part where the data self update, considering that a quota on the disk isn't something that changes frequently and that only one request on the loading of the app is enough.
To test this you should use an updated version of Cozy-stack and launch it manually. Once you're done just use the following commands:
- Use your local (updated) repo of Files (aka Drive) with a `yarn link cozy-bar` in it.
- Then start you stack server with an appropriate path to your local Files' repo:
`cozy-stack serve --appdir drive:$HOME/Repos/cozy-files-v3/build/` 
- Add your instance with a defined …
> feat: Add request to disk quota

- README.md
- src/components/Bar.svelte
- src/index.js
- src/styles/bar.css
So basically the **Cozy-Bar** gets the editor's name from the data attribute `data-cozy-app-editor` on the `[role=application]` div within the App (e.g. **Drive**) which is populated by the **Stack** while reading the `manifest.webapp` of the **Drive** App. Do you follow?
Related PR: https://github.com/cozy/cozy-stack/pull/484
> feat: Add support for editor's name in the app name

- package.json
Add a npm task to run `webpack --watch` with the webpack mobile configuration file.
> chore: add watch:mobile for mobile debugging

- src/components/Bar.svelte
We get errors when cozy-bar setups two features on mobile phone, specially visible when running on offline mode:
- disk-usage statistics
- other apps access
Best solution found: don't setup those features when `target === mobile`. Is this cool?
> fix: remove features on mobile

- src/styles/base.css
Using `100vh` for the height of the application caused some issues on some mobile browsers.
Basically `100vh` is **not** 100% of the viewport's height, but a little more than that. Why? Because why the fuck not, said browser vendors. 😎
(See https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html for more information)
So I had to get back to the old fashioned way using a `height: 100%` instead. Didn't touch the `width 100vw` because it's not an issue. For now at least.
> fix: broken layout because of vh unit on mobile browsers

- src/styles/base.css
I had to moved that style to Cozy-UI because on the mobile app it triggers some kind of ugly repaint where the nav briefly appears on top of the viewport before going down at its rightful place.
Moving that style to UI don't cause the repaint because there's no overwrite anymore so it kinda fix this bug. Furthermore, as the layout evolved I don't think it's needed anymore to have this overwrite of the layout style from the cozy-bar.
Loading an app without the cozy-bar doesn't cause any issue and with cozy-bar we don't have the repaint anymore.
What do you think @m4dz?
> chore: Remove useless layout style

- src/components/Bar.svelte
- src/index.js
We sometimes need to load the Cozy Bar in a lightweight mode, i.e. w/o navigation menus. This PR adds a `isPublic` init param (set to `false` by default) that allows to initialize the Bar w/o loading the navigation items nor the drawer.
It also forces this mode of the current page that init the bar is a `/public` URL.
> Add public mode

- src/lib/stack.js
__Issue:__ Safari seems to not display correctly `.svg` image using `Blob`, so the apps menu was full of broken icons. This PR should fix it.
__Solution:__ When the response from the stack is an`.svg` we have to use `data:base64` syntax to display in Safari but that broke other image formats which need the `Blob` usage (tested with `.png` for here) in Safari and in other browsers.
However, it seems that the binary data (all but `.svg` so) throw an error when trying to encode it in base64 using `btoa()`, so I used this error to make the distinction between `.svg` and other formats here.
> Fix apps icon display issue on safari

- src/styles/drawer.css
Used to be .8em from mobile to desktop.
It's now .5em on mobile as requested by @kelukelu
> fix: lower paddings on list in drawer

- CHANGELOG.md
- README.md
- src/components/Bar.svelte
- src/components/Claudy.svelte
- src/components/ClaudyMenu.svelte
- src/config/claudy.yaml
- src/lib/config.js
Here is my example of `cozy.yaml` for the stack:
```yaml
contexts:
beta:
onboarded_redirection: collect/#/discovery/?intro
default_redirection: drive/#/files
help_link: https://forum.cozy.io/
coming_soon:
store:
editor: 'Cozy'
name: 'Store'
slug: 'store'
category: 'cozy'
claudy_actions:
- desktop
- cozy-collect
- support
```
The actions list order will depend of the slugs list `claudy_actions` order of this context. And if the `claudy_actions` property is missing, no Claudy will be displayed.
Each slug must matched a property of the `actions` object declared in the `./config/claudy.yaml` config file (an unrecognised slug will simply be ignored).
* https://github.com/cozy/cozy-stack/pull/762
> Display Claudy according to the context + minor fixes

- src/lib/config.js
Why the bug was occurring:
I don't know why, and I did not want to introduce more regression by modifying existing code, but we got a first call to `updateApps` [here](https://github.com/cozy/cozy-bar/blob/master/src/components/Bar.svelte#L73).
I you look closely at [`updateApps`](https://github.com/cozy/cozy-bar/blob/master/src/lib/config.js#L209), it calls `updateAppsItems`, and then this last method directly set the app list into the `config` object (which should be a `state` actually).
So everything is fine except when you click on _Apps_ menu item at an early stage of the page loading. The click fires a second `updateApps`, almost synchronous with the one done above. So now we have a race between this two calls, they will both fetch the app list and update `config.apps`. Even if we …
> fix: limit race condition in updateAppsItems :ambulance:

- src/components/Bar.jsx
- src/styles/searchbar.css
Makes the search bar more flexible in terms of sizes, especially useful when the app name is long.
> fix: header element sizing for long app names

- src/components/Bar.jsx
The searchbar is still hidden by default, but can be forced to appear by placing a magic string in the URL's search part.
> feat: toggle searchbar with hidden code

- config/webpack.config.prod.js
Removing warning "You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux."
> chore: define process.env.NODE_ENV to production

- src/styles/index.styl
- src/styles/mobile_app.css
Il y a un bug sur l'application mobile Cozy Bank qui est pour l'instant la seul application mobile à utiliser réellement la cozy-bar. On voit qu'il y a un écart au niveau de l'icone menu en haut à gauche.
Avant | Après
------------ | -------------
> feat: Remove unnecessary space

- src/components/Bar.jsx
- src/index.jsx
The bar has an option called `displayOnMobile` which is false by default. It used to hide pretty much everything, [including the button to show the other apps](https://github.com/cozy/cozy-bar/blob/a03cd1ab40fb09b8c0fd5a9552e3f77961c650e8/src/components/Bar.jsx#L95-L97).
This changed after dc3a3657fa17d98447eb3339912c946d684da50b , and now this button is always displayed (which is a problem in Drive). I would like to revert to the previous behavior.
That being said, I wonder if this change would cause problems for Cozy Bank?
> fix: hide apps button on mobile

- src/components/SearchBar.jsx
I made a mistake in #123. `state.suggestions` doesn't contain the list of suggestions right away, it contains the suggestion sections, and each section has it's own array of suggestions. I was checking the length of the first array, but it's entirely possible to have a suggestion section with no suggestions in it.
I'm now properly checking each section, and I also renamed the main variable to avoid further confusion.
> fix: properly detect empty suggestions

- CHANGELOG.md
- package.json
- Documentation of cozy bar customization API [c0d08bf](https://github.com/cozy/cozy-bar/commit/c0d08bf7796dfe79b328fbac8ab51760bbe5d775)
- Persiste state on mobile with localForage [1d03fb2](https://github.com/cozy/cozy-bar/commit/1d03fb2f42228429e689567c88f9ebba8756515c)
- Add function to update accessToken [7e523a7](https://github.com/cozy/cozy-bar/commit/7e523a714e956f76b9dfb48ac76965bc233c2758)
- Save apps on redux store [6037eb7](https://github.com/cozy/cozy-bar/commit/6037eb74d645433e78986b5ecf9aa38b719a49e7)
- chore: Add bundlesize script to monitor build size 🔧 [a9b95f1](https://github.com/cozy/cozy-bar/commit/a9b95f101446171cbce310413e38c725cf9d9ead)
- feat: Remove own app on mobile AppsList [1692363](https://github.com/cozy/cozy-bar/commit/16923634c5e0affe46e3267f8f75724d6e89322 …
> 💎 Release v4.5.5

- src/components/Bar.jsx
- src/components/Drawer.jsx
- src/components/Nav.jsx
- src/index.jsx
- test/__snapshots__/index.spec.js.snap
In bank, we need to do some custom things when we log out of the mobile app. So we needed to pass an `onLogOut` handler to the cozy-bar. That's the purpose of this PR.
> feat: add onLogOut option on init

- package.json
- src/components/SearchBar.jsx
- yarn.lock
Put a debounce in the sent message to get search results.
But it appears there is a lot of obscur code in there and in cozy-drive intent.
> feat: debounce search results

- src/components/Bar.jsx
In 76719e5c98f1ae7a849265231ef5438c623e08b8 we enable search bar.
But we only want to enable it on Cozy Drive.
For now, we only check the `currentApp` name, but with time we will use the stack API.
> feat: enable search bar for Cozy Drive only

- src/components/SearchBar.jsx
In #180 , we debounced the function that receives the search results. This worked to a degree, but not quite, because sometimes the results come in one after the other with a delay greater than 250ms, and we still get the flashes of results.
Instead, I suggest we debounce the calls to the function that makes the query to the services. So if the user quickly types "hey what's up", we only fetch the suggestions once, when he/she's done typing.
It's still possible to get flashes of course, if you wait just over 250ms and start typing again. But it's less frequent.
> fix: debounce suggestion fetch requests

- src/components/SearchBar.jsx
- src/styles/searchbar.css
Minor style update: when the searchbar isn't focused, we reduce it's opacity.
> style: fade search bar on blur

- README.md
- src/components/AppsList.jsx
- src/components/Bar.jsx
- src/index.jsx
- src/lib/reducers/apps.js
- test/__snapshots__/index.spec.js.snap
- test/index.spec.js
We don't use the editor as application name prefix anymore but a dedicated property.
(this property is already used in `cozy-store`)
> Use app name_prefix instead of app editor

- src/styles/bar.css
A CSS ordering bug causes the nav-bar to be above the drawer menu on iOS.
Normally (on browsers) the bar when drawer is opened has a z-index of 90 but on iOS it is 31 because the rule is loaded after.
Since the rule with 31 is normally overrided and is causing the bug, I deleted it.
Ordering bug : 
on iOS (31 after 90 and 90 is discarded) : 
on other browsers (90 after 31 and 31 is discarded) :
> fix z-index of menu on ios

- src/lib/stack.js
A minor thing, but:
- The requests on the stack had no `content-type` header, so the stack can answer whatever it wants. It uses json most of the time, but for errors for example, it sometimes use plain text unless you tell it not to.
- When there's an error, there's no `data` in the JSON, so I made sure we get the actual error instead of some random runtime error.
> fix: Better JSON handling

- src/styles/drawer.css
Also make nav elements in drawer clickable while adding safe space on Iphone X and prevent scrolling background on iOS
Fixes: #216
⚠️ Side effect: Displaying the drawer will switch off minimal UI. There's no way I can bypass that but it seems like a small price to pay.
> fix(Drawer): Fix drawer position on mobile devices

- src/components/AppIcon.jsx
- src/components/AppIcon.spec.jsx
- src/components/AppsList.jsx
- src/components/Bar.jsx
- src/components/ComingSoonModal.jsx
- src/components/Drawer.jsx
- src/components/Nav.jsx
- src/components/__snapshots__/AppIcon.spec.jsx.snap
- src/proptypes.js
- test/jestLib/setup.js
- test/lib/api.spec.js
In preparation for another PR, I've refactored the `AppIcon` code.
* `AppIcon` understands directly the `app` object
The AppList had 6 props related to the `app` object. The `AppList`
had to know all this properties, and forced the creation of useless
props on the `AppIcon`.
[Components/functions should know as little as possible of each other
API][Demeter].
Now the `AppList` [only responsibility][responsibility] is simply to render a list of `AppIcons`.
The `AppIcon` responsibility is to render the `Icon` and text directly from
the `app` object.
* Threading of the `toggleComingSoon`
The `toggleComingSoon` prop was passed from component to component since
the state of the modal was stored in the `Bar` state. It forced every component
in the middle to know about this function that they did …
> refactor: AppIcon

- package.json
This way we cannot forget to build before publishing.
> chore: build before publish

- src/config/claudyActions.yaml
While migrating from Cozy-Collect to Cozy-Home, we are temporarly removing the Claudy `cozy-collect` action to avoid keeping both Cozy-Collect and Cozy-Home too long on registry.
> Remove cozy-collect action

- config/webpack.config.base.js
- config/webpack.config.extract.js
- config/webpack.config.inline-styles.js
- src/components/Apps/AppsContent.jsx
- src/components/Apps/index.jsx
- src/components/Drawer.jsx
- src/components/SearchBar.jsx
- src/components/Settings/SettingsContent.jsx
- src/components/Settings/index.jsx
To prepare the bar for customization, this PR :
* Use relative paths for Webpack options and loader options
* Use relative paths to `src/` for all `import` statements
> Use webpack module/related paths

- package.json
Le build est rouge depuis très longtemps (mai) pour une histoire de taille... je pense que ce n'est donc pas indispensable sinon on aurait passé du temps à résoudre le problème.
> chore: Update maxSize bundle

- src/index.jsx
- test/index.spec.js
Realtime need an URL, so we generate one which mean nothing.
Realtime should be able to handle `domain` and `secure` parameters, see https://github.com/cozy/cozy-libs/pull/21
> Fix realtime  initialization

- src/lib/store/index.js
Temporary removing of this feature to avoid 'infinite fetching' state stored in localStorage
> Disable redux-persist for apps

- src/index.jsx
- src/lib/stack.js
This PR makes the realtime handle correctly the cozyURL parameter passed by mobile apps.
Also, it adds a new ssl parameter which can be used to force secure protocols used by the bar. Ideally, apps will soon be able to pass this parameter, based on their environment. See [this PR on cozy-scripts](https://github.com/CPatchane/create-cozy-app/pull/810/)
> Better realtime

- src/lib/middlewares/appsI18n.js
`actualLang` was not a really good name.
> Rename actualLang to currentLang

- src/components/Apps/AppItem.jsx
- src/lib/stack.js
- src/proptypes/index.js
Ensure that the mime type of an SVG icon is always defined.
This issue seems to be caused by a bug in Cordova, also occurring on iOS10.
See also https://github.com/cozy/cozy-home/pull/989 and https://github.com/cozy/cozy-bar/pull/313
> Fix SVG icons for cordova and iOS10 📱

- src/index.jsx
This warning was here to inform about the future change of how the
cozy-bar is initialized.
After discussing with @kosssi, the cozy-bar initialization will still
be possibile with an url, as the mobile apps are needing it.
> Remove url param warning

- config/webpack.config.prod.js
- package.json
- yarn.lock
This fix an issue about due to UglifyJS `TypeError: Super expression must either be null or a function`. 
Terser is recommended and [will be used by default by Webpack 5](https://github.com/webpack-contrib/terser-webpack-plugin/issues/15#issuecomment-421388132)
> 🚨Prefer Terser to UglifyJS

- config/webpack.config.base.js
- package.json
- src/components/Apps/AppItem.jsx
- src/components/Apps/AppItemPlaceholder.jsx
- src/components/Apps/AppNavButtons.jsx
- src/components/Apps/AppsContent.jsx
- src/components/Apps/index.jsx
- src/components/Banner.jsx
- src/components/Bar.jsx
- src/components/Claudy.jsx
- src/components/Drawer.jsx
- src/components/SearchBar.jsx
- src/components/Settings/SettingsContent.jsx
- src/components/Settings/StorageData.jsx
- src/components/Settings/index.jsx
- src/components/SupportModal.jsx
- src/index.jsx
- src/lib/api.js
- src/prepareReact.js
Since we want the bar use the React/Preact provided by the application, the bar must check in the global scope. Only if no frameworks found, the bar will use React bundled with it.
Pro: No more broken apps even for the old ones
Cons: We still continue to bundle React/ReactDOM with the cozy-bar
> Use default React bundled if not found

- config/aliases/globalReact.js
- config/aliases/globalReactDOM.js
- config/webpack.config.base.js
Mixed aliases work as wanted, alias is an alias even in the alias webpack property.
> Require modules instead of mixed aliases

- src/index.jsx
- src/lib/api/helpers.js
- src/lib/api/index.js
By this way, whatever you charge the bar before or after the application script, the bar will look for React/ReactDOM in global scope only on init() for its working (and will start serving the API only after the init).
Should make the bar more robust for its usage.
> Handle modules only on init by the app

- package.json
- yarn.lock
If I am not mistaken, preact is no longer a dependency as the bar
bundles React by default.
React also should not be a dependency as the bar is bundled. It should be a dev dependency ?
> chore: Remove preact dep

- src/components/Bar.jsx
- test/components/Bar.spec.jsx
Previously, if the user had opened its app while Internet was not
connected, the bar would never load the apps again.
Now, when the drawer opens, we check if we already successfully 
fetched the apps, and if not, we try to fetch again.
> feat: Re-fetch apps if app not loaded and drawer opens

- package.json
- src/index.jsx
- src/lib/store/index.js
- test/store/index.spec.js
The delaying of the instantiation of the store changed the module level variable to a function level variable. This meant that there could be several store instances and led to a bug where the Bar was not properly refreshed after a dispatch (the exported Bar component would dispatch on a store, where the connected store was another one).
> Fix only 1 store

- src/components/Apps/AppItem.jsx
Banks has not the same appId on iOS and and Android. This PR fix this issue
> fix: Banks on iOS has not the same appId

- package.json
- yarn.lock
This upgrade made some errors during develoment build
```
WARNING in ./src/lib/intents.js 6:9-22
"export 'cozyFetchJSON' was not found in './stack'
@ ./src/components/SearchBar.jsx
@ ./src/components/Bar.jsx
@ ./src/index.jsx
WARNING in ./src/lib/intents.js 137:22-35
"export 'cozyFetchJSON' was not found in './stack'
@ ./src/components/SearchBar.jsx
@ ./src/components/Bar.jsx
@ ./src/index.jsx
WARNING in ./src/lib/reducers/apps.js 101:23-28
"export 'default' (imported as 'stack') was not found in '../stack'
@ ./src/lib/reducers/index.js
@ ./src/index.jsx
WARNING in ./src/lib/reducers/apps.js 162:50-55
"export 'default' (imported as 'stack') was not found in '../stack'
@ ./src/lib/reducers/index.js
@ ./src/index.jsx
WARNING in ./src/index.jsx 207:12-17
"export 'default' (imported as …
```
> fix: Revert "chore(deps): update dependency babel-loader to v8"

- src/lib/stack.js
Without the `//` the URL doesn't work on browsers
> Correctly determine cozy-bar URL usage

- src/lib/stack.js
URL beginning by `//` was broking realtime, since we got now the SSL information we can always use the protocol to build the COZY_URL
> Always use the protocl for COZY_URL by default

- package.json
- src/components/Bar.jsx
- test/components/Bar.spec.jsx
- test/components/__snapshots__/Bar.spec.jsx.snap
- yarn.lock
Currently, the SearchBar is activated only on Drive and when not on a public page. 
This bar is hidden with a media-query, but this media-query is not enough for some iPad. So we decided to disable the search bar when we are in a cordova app
> fix: Disable searchBar on mobileApp

- src/components/Bar.jsx
- src/components/SupportModal.jsx
- test/components/__snapshots__/Bar.spec.jsx.snap
Due to React and Preact difference, where React append the destination element with the Modal and Preact replace the content of the destination by the Modal, we change the destination which was body to a dedicated node.
> fix(Modal): Put Modal into a dedicated place insteed of body

- config/webpack.config.base.js
Webpack process differently absolute path vs relative path for `node_modules`, it's better to avoid absolute path.
> Use relative node_modules in webpack config

- src/components/Apps/AppItem.jsx
- src/components/Apps/AppsContent.jsx
- src/components/Drawer.jsx
- src/lib/store/index.js
- test/components/AppItem.spec.jsx
* Persisted locale was causing issue on locale changing and it was not used
* Now the drawer is closed on app item click if:
* target app is **web** and current app is **mobile**
* target app is **mobile** and current app is **mobile**
* target app is **mobile** and current app is **web**
> Remove persisted locale + close drawer on app switch

- src/lib/reducers/apps.js
The whole onboarding is now part of the stack.
See also https://github.com/cozy/cozy-store/pull/547 and https://github.com/cozy/cozy-home/pull/1113
> chore: Remove the onboarding from the hidden apps

- src/components/Drawer.jsx
Listening for gestures on body was causing a bug on Android: after
closing the Drawer, a touch-events: none persisted on the body and the
scrolling was locked.
> fix(Drawer): Listen gesture on html element

- src/components/Bar.jsx
- src/index.jsx
- src/lib/api/index.js
- src/lib/reducers/theme.js
- src/styles/theme.styl
- test/components/Bar.spec.jsx
- test/components/__snapshots__/Bar.spec.jsx.snap
- test/lib/api.spec.js
Objectif : Permettre la surcharge des couleurs lors d'un changement de thème de la barre.
Pour l'instant ce n'est fait que pour le thème 'primary', et uniquement là où il surcharge la vue mobile.
>  feat: Allow custom overrides in the theme 

- package.json
- src/components/Bar.jsx
- yarn.lock
We import a polyfill for `Object.assign` from `core-js`. Since version 2.6.4, this somehow also polyfills `fetch`, which in turn causes other problems.
The initial reason for using the polyfill is discussed [here](https://github.com/cozy/cozy-bar/issues/172) but it boils down to supporting `Object.assign` calls in cozy-ui on IE11. In the meantime, we transpile cozy-ui so `Object.assign` calls are transformed when needed, but also we dropped IE11 support. So I suggest we remove this dependency altogether from the bar.
> fix: Stop polyfiling Object.assign

- src/components/Apps/AppItem.jsx
We don't need to override the current application since it breaks some use case (coming from deeplink for instance)
> feat: No need to override anymore if it's the same app

- src/lib/stack-client.js
- src/lib/stack.js
Was removed by accident when refactoring the stack to handle cozy-client
> Get back settings app handling

- src/components/Apps/index.jsx
Do not handle a click inside a bar's modal as an outside click, and keep any Drawer or menu opened.
The Modal placeholder should be passed as a context property to all children component, we should maybe use some kind of Provider or HOC.
> Handle modal click

- src/styles/apps.css
This avoids white text on white background on systems with dark theme
| Before | After |
|--------|-------|
|![image](https://user-images.githubusercontent.com/1606068/55496152-aa803200-563e-11e9-9c34-a800db1b485b.png)|![image](https://user-images.githubusercontent.com/1606068/55496109-9e947000-563e-11e9-841c-3728f4084e7a.png)|
> fix: Set color on nav apps main button

- src/styles/apps.css
Since the active AppItem is now clickable, we should not override the cursor type
> fix: AppItem cursor

- package.json
- yarn.lock
Upgrade cozy-device-helper to fix deeplinking issue on iOS 12 2 +
> fix: Upgrade cozy-device-helper

- src/components/Apps/AppItem.jsx
- test/components/AppItem.spec.jsx
- test/components/__snapshots__/AppItem.spec.jsx.snap
This PR is a quick try to answer to our need of passing argument in an AppLinker href in Cozy-Bar.
~~The idea is to be able to override current href using Component inheritance:~~
~~Another alternative should be to implement directly query parameter as an `AppLinker` prop and let it generate the href. What do you think ?~~
How this should work:
```jsx
import 'AppItem' from 'original-bar/src/components/AppItem'
AppItem.buildQueryParams = (props, context) => ({
foo: 'bar'
})
export AppItem
```
> Allow overriding AppItem href

- test/components/AppItem.spec.jsx
- test/components/__snapshots__/AppItem.spec.jsx.snap
React was complaining that the src attribute of the img tag
rendered by AppItem was invalid.
> fix: Removed React warning during tests

- src/index.jsx
CozyClient seems to import somewhere React or a React based library so it this won't work with Preact in Cozy-Home, require CozyClient on init fix that issue.
This issue was causing a blank bar in cozy-home.
> Always import CozyClient when needed by bar

- src/index.jsx
When the cozy-bar instantiates its own cozy-client, it needs a valid `uri`. The protocol was missing. 
Note that if the app initializes the bar with a `cozyURL`, it has to provide an URL with protocol : https://github.com/cozy/cozy-bar/blob/master/src/index.jsx#L200
> fix: Add protocol to default stack url

- src/components/Apps/AppItem.jsx
- test/components/__snapshots__/AppItem.spec.jsx.snap
App URLs with query string  were not properly encoded.
Let AppLinker manage the href with query string.
> Append query string in AppLinker href prop 🚑

- src/components/SearchBar.jsx
React-dev-tools sends message but the bar log every message. 
See https://github.com/facebook/react-devtools/issues/812
> chore: Remove log for React dev tools message

- src/components/SearchBar.jsx
URL should be enough is a vaste majority of use case. But in my case, I've several `Drive` installed and I got a few warnings complaining about the key not being unique.
> fix: Key should be uniq

- package.json
We have issues with the cozy-stack-client version on drive. It seems to come from here
> fix: cozy-client should be a peer dep

- src/styles/index.styl
Some utility classes were called but they weren't in the transpiled cozy-ui so I explicitely added them to cozy-bar styles.
> fix: Add missing CSS utils

- config/webpack.config.base.js
- config/webpack.config.extract.js
- config/webpack.config.inline-styles.js
- config/webpack.config.jsx.js
- src/styles/index.styl
This PR goal is to fix the bugs we have when we use a cozy-bar with a cozy-ui version that is not the same as the host app cozy-ui version.
This problems exists because the cozy-bar uses the transpiled version of cozy-ui, thus we could have two stylesheets that could override each other.
The solution explored here is to stop using the transpiled version of cozy-ui. The bar transpiles its own cozy-ui and use a custom classname scheme for cozy-ui's classnames. This way, there is no more conflicts between the bar's cozy-ui stylesheets and app's cozy-ui stylesheet.
This was tested on Banks, in which we had this issue: they are all gone.
> fix: Avoid cozy-ui stylesheet conflict with the apps

- config/webpack.config.base.js
The goal of this PR is to go back using an `exclude` clause. It will allow custom repositories to transpile override directories.
> Go back to config excluding node_modules

- package.json
- yarn.lock
This dependency is not used in the actual (original) cozy-bar. Keeping this dependency forces us to update it here every time we need an update on custom repositories.
> Remove dependency to cozy-harvest-lib

- config/webpack.config.base.js
- config/webpack.config.extract.js
- config/webpack.config.inline-styles.js
- config/webpack.config.jsx.js
- src/styles/index.styl
This reverts commit ff86f9b939950a3832be8f041f3c52168fee009c.
We had troubles with the update of the webpack config to bundle not transpiled cozy-ui. Related: https://github.com/cozy/cozy-bar/pull/582
I think the plan could be to revert these changes in master and npm's `latest` channel, then do it in a branch and the npm's `next` channel.
> Revert "fix: Avoid cozy-ui stylesheet conflict with the apps"

- config/webpack.config.inline-styles.js
When sourcemap is enabled in css-loader, the style-loader injects a
`link` tag pointing to a blob generated dynamically. This leads to a
flash of unstyled content (FOUC) on the bar. Disabling the sourcemap
makes the style-loader inject a `style` tag and we don't have a FOUC
anymore.
> fix: Avoid FOUC on mobile

- src/components/Apps/AppItem.jsx
- test/components/AppItem.spec.jsx
~~When serving an app locally with option `--appdir`, the app is listed in the endpoint `/apps/` but all fields are `undefined`.~~
If a document has been created by mistake in DB `io.cozy.apps`, it is returned in the `/apps/` endpoint response with all its fields being `undefined`.
This PR ensure that an `undefined` href will not make the whole app to crash when building the app url.
> AppItem: Prevent malformed URL to make the app crash

- config/webpack.config.base.js
- config/webpack.config.extract.js
- config/webpack.config.inline-styles.js
- config/webpack.config.jsx.js
- src/components/Bar.jsx
- src/styles/index.styl
- test/components/__snapshots__/Bar.spec.jsx.snap
This is a new attempt to transpile and bundle cozy-ui to avoid messing with the app's cozy-ui stylesheet.
Previous attempt (https://github.com/cozy/cozy-bar/pull/582) was done with a bad timing and bugs were found in the middle of a rush, so we had no choice but revert it.
> Bundle cozy-ui

- src/components/SearchBar.jsx
- src/index.jsx
- src/lib/realtime.js
- src/lib/reducers/apps.js
- src/lib/reducers/context.js
- src/lib/reducers/settings.js
We should not have any eslint warnings. I disabled the warnings via `eslint-disable-next-line no-console`.
There were also occurences of `console.log && console.log('my log')` that I do not think are necessary. Do
you have any idea @gregorylegarec why the call needed a check ?
> chore: Remove console warnings

- src/components/SearchBar.jsx
We can have MUI component loaded inside an iframe. It works
pretty well on Chromium and Safari, but not on Firefox
'cauz of this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=548397
Our CozyMUITheme is based on getComputedStyle, but since the iframe
is hidden, firefox crash during its creation.
The workaround is to not use display:none, but instead visibility
hidden with height & width = 0
(Our bug case was the searchbar on Drive)
> fix: Change iframe visibility

- package.json
- src/components/Settings/SettingsContent.jsx
- src/components/Settings/helper.js
- src/components/Settings/index.jsx
- src/locales/en.json
- src/queries/index.js
- test/components/Settings/helper.spec.js
- yarn.lock
- Display a button if the cozy is concerned by a Premium offer 
- Use cozy-client and queryConnect to get the infos 
I think we do sometimes the request from old code but also from this new one, but I think I'll be easier to migrate the old code in this way and old code set stuff in the redux store and I didn't want to create a too big refacto for now. 
Let's do that in the future work :)
> feat: Display view offers buttons

- package.json
- src/components/Settings/helper.js
- src/components/Settings/index.jsx
- test/components/Settings/helper.spec.js
- yarn.lock
check cozyclient version before calling new functions 
Wanted to add a few tests for the component, but it requires more work since enzyme et enzyme react adapter are pretty old. An upgrade breaks other tests...
> feat: Check cozyclient version to call instance info

- src/components/Settings/helper.js
- src/components/Settings/index.jsx
- src/lib/stack-client.js
- test/components/Settings/helper.spec.js
On old CozyClient version, we can't use queryConnect since we have errors with ObersableQueries. 
In order to avoid that issue, we export the "new component" only if we can checkPremium. (tested on current contact stable) 
Also, we can't read cozyclient's version from the static import of cozy-client. We need to read it from the cozy-client's instance passed to the bar
> fix: Better support for old cozyclient version

- src/components/Apps/AppItem.jsx
- src/components/Settings/helper.js
- src/config/excludedApps.yaml
- src/lib/reducers/apps.js
- src/lib/stack-client.js
- test/components/Settings/helper.spec.js
- test/components/__snapshots__/AppsContent.spec.jsx.snap
- test/lib/stack-client/stack-client.compare.spec.js
This PR brings the app list in line with the behavior on the home page:
- No Cozy prefix
- Support translated names
- Display Settings
I did 475512012cd1cb831ad2f2df425b13999114dcff anticipating I'd need it for using `applicationsModel`but didn't end up using it. I still think it's better like this but we can also remove this commit from the PR.
> Better app names

- src/styles/apps.css
Fix for https://trello.com/c/6KHIM8PO
If an app doesn't load cozy-ui, normalize.css is missing and button default to 11px instead of 16px.
This change push the 1rem to a specific place to avoid having to load cozy-ui if not needed.
> fix: App name size should be 1rem

- package.json
- yarn.lock
We added a few functions in our minilog fork. We should use it ;)
> fix: Use cozy fork for minilog

- src/lib/reducers/apps.js
- src/lib/reducers/apps.spec.js
We make a request to /settings/context to get the "Default App", in order to make the link "Back to home" in the cozy bar. But with a self hosted cozy, we don't have a context by default and we don't have a default home slug defined.
So two solutions: 
- self hosted can create a context and add a default_redirection param equal to "home/"
- Edit the cozy bar to get the "HOME" slug if the default_redirection is not defined. 
I renamed homeApp to DefaultApp since we can have a different app
> feat: Better default app support for self hosted cozy

- .travis.yml
- package.json
- yarn.lock
travis-deploy-once causes a [deployment problem](https://travis-ci.org/github/cozy/cozy-bar/builds/718566049#L1113)
since it depends on a @babel/preset-env. This causes a dependency
resolving problem since the @babel/preset-env of travis-deploy-once
cannot find the @babel/plugin-transform-regenerator that is under
the node_modules of the root @babel/preset-env.
It's a bit clearer when seeing the structure:
```
node_modules
travis-deploy-once
node_modules
@babel/preset-env
❌ cannot find the @babel/plugin-transform-regenerator since
it needs to go up AND down, which is not covered by
the node dependency solving mechanism
@babel/preset-env
node_modules
@babel/plugin-transform-regenerator
```
Anyway, travis-deploy-once is deprecated and [semantic-release advocates
to use build …
> chore: Remove travis-deploy-once

- src/index.jsx
- src/index.spec.jsx
Otherwise we have to do cozy.bar.default.init
> fix: Do not use export default but only export

- src/components/Apps/AppNavButtons.jsx
One icon had not been automatically migrated because of a ternary
condition.
> feat: Use svgr icon in AppNavButtons

- package.json
cozy-ui stylus utility helpers behave differently if we have CSSMODULES
to true or false. If the CSSMODULES is not set to false, we end up
with :global selectors in the resulting CSS file. This does not work
well with safari which ignores the rules under :global.
> fix: Deactivate cssmodules when transpiling

- src/queries/index.js
client.get is deprecated. Q is preferred as it can be used statically (no
need for a cozy-client) and more versatile as you can build any query
with it (with client.find and client.get, you are limited, to Q::where()
and Q::getById()).
> Remove cozy-client warning

- package.json
This is necessary after the new features added to cozy-bar.
No way around it at the moment, best would be to remove react
> ci: Make max bundlesize higher

- package.json
- yarn.lock
Old version broke cozy-banks CI because of old minilog
> feat: Upgrade cozy-realtime to latest

- src/components/Apps/ButtonCozyHome.jsx
- src/components/Apps/ButtonCozyHome.spec.jsx
- src/components/Bar.jsx
In case of race condition, error handling is done by native javascript
(can't call() from undefined)
> fix: Always display home icon in Webview

- package.json
- src/styles/apps.css
- 48x48 container, 32x32 img, marginRight 4px
- Aligned center on X and Y axis
➡ As per the design spec
https://trello.com/c/tKnoBX2y/336-%F0%9F%90%9B-clignotement-du-titre-de-lapp-%C3%A0-louverture-dune-application
> fix: Use correct dimensions on flagship buttons

- package.json
We have issue when installing cozy-bar >= 8.4.0 & cozy-client >= 27.10.X.  
By removing the need of "dep" and changing them to peerDep & devDep, it solves the issue. 
Issue was: 
An unexpected error occurred: "expected hoisted manifest for \"cozy-bar#cozy-client#cozy-ui\"
> fix: Dep & PeerDep

- .releaserc
- .travis.yml
- CODEOWNERS
- package.json
- yarn.lock
In order to have a better workflow, we're going to deploy v7 releases automatically to **npm** instead of manually. Basically, `v7-stable` will be v7 `master` branch and is supposed to work exactly the same (you can't push commit to it, it handles semantic-release on v7.x, etc.)
- Added a `.releaserc` file to allow that feature
- Updated `.travis.yml` to handle that feature
- Updated `CODEOWNERS` to reflect the current state of affairs
- Updated `semantic-release` because the old version did not handle multiple feature branches
> feat: Add deploy stage to v7-stable

- src/components/Bar.jsx
If searchbar ever renders in FlagshipApp, this will currently trigger
a breaking bug with iframes CSP issues.
As of now we just ask the cozybar to not render the searchbar when
we're in flagship so the issue does not exist
> fix: Make sure searchbar doesn't render

- src/components/SearchBar.jsx
This handled cozy notes open when Drive needs to provide URL
fix https://github.com/cozy/cozy-drive/pull/2663#discussion_r938671963
on v7 https://github.com/cozy/cozy-bar/pull/770
> feat(SearchBar): call onSelect when it's provided

- src/components/SearchBar.jsx
- src/components/__snapshots__/Bar.spec.jsx.snap
See PR description of https://github.com/cozy/cozy-bar/pull/773
>  feat(SearchBar): fetch and open note once clicked on a suggestion

- src/components/SearchBar.jsx
Problem was detected by:
https://github.com/cozy/cozy-drive/pull/2663?notification_referrer_id=NT_kwDOAH-dRrI0MTM4NzMwMjUyOjgzNjMzMzQ&notifications_query=is%3Aunread#discussion_r946530786
notes URL were not used to redirect, once clicked.
By fixing that bug, I realized the postMessage onSelect function could not be sent through postMessage. Becasue postMessage serializes the object before sending it.
[An object could not be cloned](https://stackoverflow.com/questions/42376464/uncaught-domexception-failed-to-execute-postmessage-on-window-an-object-co)
Fetching URL is now done inside Cozy-Bar scope
> feat(SearchBar): fetch and open note once clicked on a suggestion

- src/components/SearchBar.jsx
it removes warnings in Drive cause by Searchbar
> fix(warning): mark as UNSAFE component will mount

- src/styles/settings.css
An extra spacing came only on Safari browser
removing display block prevents the extra margin
> fix(styles): Safari margin of Settings Menu are removed

- src/components/SearchBar.jsx
Since we send a (fake) message via postMessage,
Cozy Drive's intent will catch it and
send the _all_docs request. Like that
we warm up the query and the data and
we expect to give a better UX like that.
> feat: Launch stack request on focus

- src/components/Apps/AppItem.jsx
AppLinker needs app props now. Specially within the flagship app. 
`app` props is required and it's a BC of cozy-ui. We didn't upgrade the call yet. This is now done.
> fix: AppLinker needs app props now

- src/components/Banner.jsx
- src/locales/en.json
- src/locales/fr.json
If the html document contains a "moved" descriptor, we will display the correct translation.
Also, we won't display banner CTA as there is no link available in the metadata.
> feat: add translations for banner moved (VO-46)

- package.json
- yarn.lock
BREAKING CHANGE: you must have `cozy-ui >= 111.5.0`
> feat: Upgrade cozy-ui to 111.5.0

- src/lib/reducers/apps.js
The `apps.hidden` flag will be used to hide apps in home, store and bar
> [PRD-538] feat: Hide apps by flag

- src/lib/reducers/apps.js
The `apps.hidden` flag will be used to hide apps in home, store and bar
Copy of https://github.com/cozy/cozy-bar/pull/854
> feat: Hide apps by flag

- package.json
- src/components/AppsMenu/AppsMenuContent.jsx
- src/components/AppsMenu/components/AppItem.jsx
- src/components/AppsMenu/index.jsx
- src/components/UserMenu/UserMenuContent.jsx
- src/components/UserMenu/index.jsx
- yarn.lock
Solves to issues :
- If I am on settings on "Appearance" page and I click on "Manage profile" from cozy-bar UserMenu, it will navigate to "Profile" page but the UserMenu stayed open
- On flagship app, we need to close the AppsMenu when opening a app because the home is always alive in a separate webview. So when we were going back to the home,  the UserMenu stayed open
Todo :
> fix: Close modals when navigating

- src/components/UserMenu/components/AvatarMyself.jsx
By using src attribute of Avatar from mui to display a picture, we benefit from mui classes and object-fit: 'cover'.
> fix: Avoid strech in bar avatar
