.tx/config, package.json, src/components/Bar.svelte, src/components/NavigationItem.svelte, src/components/NavigationSection.svelte, src/index.js, src/lib/i18n.js, src/locales/en.json, yarn.lock
**⚠️  THIS ONE AWAIT ~~#1 &~~ #2, DO NOT MERGE BEFORE THEM**
Add localisation throught polyglot
=> Add localisation

config/webpack.config.dev.js, config/webpack.target.split.js, config/webpack.target.standalone.js, package.json, src/components/NavigationItem.svelte, src/components/NavigationSection.svelte, src/index.js, src/lib/stack.js, src/styles/navigation_section.css, yarn.lock
This PR add proper loading for apps icons in cozy-bar, w/ a lazy loader that allow us to fallback to a placeholder icon if the given URL returns an error (like a 404).
It also brings some improvement to lightweight final build.
=> Apps icons and minor improvements

config/webpack.target.mobile.js, config/webpack.target.split.js, package.json, src/components/Bar.svelte, src/styles/bar.css, src/styles/base.css, src/styles/index.css, src/styles/mobile_app.css
This PR add a new build target for mobile app which introduces a `__TARGET__` compil var and use it to disable some chunks of code like the drawer.
=> Add mobile app build flavor

src/styles/bar.css
According to https://github.com/cozy/cozy-ui/pull/43/files#diff-d73d1084b316729ae32f7399ce5c27e9R21, this PR fix the BAR z-index to stay consistent w/ Cozy-ui (thanks @GoOz)
=> Update BAR z-index

src/components/NavigationItem.svelte, src/lib/stack.js
Asynchronously loaded base64 encoded blob URI #bullshitBingoYeah \o/
=> Fix perms on icons

src/styles/navigation_item.css, src/styles/navigation_section.css
=> feat: Add hover effect on pop menu links + clean up

src/lib/stack.js
=> fix: isInteger now tests a number and not a string

src/components/Bar.svelte, src/components/NavigationSection.svelte, src/index.js, src/lib/i18n.js
Expose setLocale to change the cozy bar locale from the application
=> Force cozy bar to rerender when locale change

src/styles/bar.css
Increase bar's min-height on mobile as asked by our beloved designer.
That's pretty much it.
=> feat: increase bar's height

src/components/NavigationItem.svelte, src/lib/config.js
=> feat: display app names in drawer instead of slugs

src/components/Drawer.svelte, src/components/NavigationGroup.svelte, src/components/NavigationItem.svelte, src/components/NavigationSection.svelte, src/styles/drawer.css, src/styles/navigation_item.css, src/styles/navigation_section.css
=> Better apps navigation menu

src/components/Bar.svelte, src/index.js
Please @m4dz, could you review these changes?
=> fix: update initialization on public mode

src/components/Bar.svelte, src/components/NavigationGroup.svelte, src/components/NavigationItem.svelte, src/config/menu.yaml, src/locales/en.json, src/styles/bar.css, src/styles/navigation_item.css, src/styles/navigation_section.css
=> Add beta status

src/index.js
=> feat: Show a warning when the bar cannot find the domain or token

src/styles/navigation_item.css
Removes hover effect and pointer cursor for Coming Soon apps. What do you think ?
=> feat: remove hover for coming soon apps :lipstick:

src/components/Claudy.jsx, src/lib/intents.js, src/styles/claudy.css
⚠️ Need https://github.com/cozy/cozy-client-js/pull/194 to be merged before merging this PR. ⚠️
=> [WIP] Intent library update + minor improvements

src/components/Bar.jsx, src/index.jsx, src/lib/stack.js
- Option to display even if we are on mobile
- Do not add '//' in front of the cozy URL if we are on mobile since the protocol there is 'file://'
=> Fix mobile

config/webpack.config.base.js, src/components/Bar.jsx, src/index.jsx
First step toward customizable cozy-bar.
=> Refactor bar render

jest.config.json, package.json, src/components/Bar.jsx, src/components/Claudy.jsx, src/components/Drawer.jsx, src/components/Nav.jsx, src/components/SupportModal.jsx, src/index.jsx, src/lib/BarStore.js, src/lib/api.js, src/lib/api.spec.js, src/lib/content.js, src/lib/reducers.js, src/lib/store.js, yarn.lock
Exposes API to control the bar left/center/right content
JS API :
```js
const { setBarLeft } = cozy.bar
setBarLeft("<span>Hello</span>")
```
Also `setBarRight` and `setBarCenter`
React API :
```js
const { BarLeft } = cozy.bar
const MyComponent = <div>
<BarLeft>Hello</BarLeft>
</div>
```
First PR with without redux : https://github.com/cozy/cozy-bar/pull/108
=> Bar hooks with redux

src/components/Bar.jsx, src/index.jsx, src/lib/I18n.js, src/lib/api.js, src/lib/api.spec.js, src/lib/locale.js, src/lib/reducers.js
=> fix: setLocale now acts on the store -> lang is updated on the bar

src/styles/drawer.css, src/styles/navigation_item.css
=> Reduce item size in apps lists :lipstick:

src/components/SearchBar.jsx, src/locales/en.json, src/styles/searchbar.css
- replaces the magnifying icon with a spinner during the search
- displays a message when no results are found
=> feat: search spinner and empty results

src/components/Bar.jsx, src/components/Claudy.jsx, src/styles/bar.css, src/styles/base.css
=> Fix bar elements

src/components/Bar.jsx, src/components/Settings.jsx, src/locales/en.json, src/styles/bar.css
This reverts commit 75a0b595d30f76e5f0d421d21b43754a25d94374.
=> Revert "fix: remove beta status :sparkles:"

src/components/SearchBar.jsx, src/styles/searchbar.css
Related to https://github.com/cozy/cozy-drive/pull/509
=> feat: add icon to searchbar result

CHANGELOG.md, package.json
=> release: prepare v4.5.2

CHANGELOG.md, package.json
- Storage computing in bytes ✏️
- Use I18n from cozy-ui
=> 💎 Release v4.5.3

README.md
[Actual preview here!](https://github.com/cozy/cozy-bar/blob/c0d08bf7796dfe79b328fbac8ab51760bbe5d775/README.md#customizing-the-content-of-the-bar)
=> chore: document cozy bar customization API

src/components/AppsList.jsx, src/index.jsx, src/lib/reducers/apps.js, src/lib/reducers/index.js
Sur les applications mobile il n'y a pas besoin d'afficher l’icône de l'application :
| Before | After |
|--------|------|
| <img width="331" alt="capture d ecran 2017-12-12 a 10 46 21" src="https://user-images.githubusercontent.com/1135513/33877787-bb74f416-df29-11e7-9e23-81adcf5ff54b.png"> | <img width="330" alt="capture d ecran 2017-12-12 a 10 37 35" src="https://user-images.githubusercontent.com/1135513/33877798-c5d37cd4-df29-11e7-988b-5f0bf565c934.png"> |
=> feat: Remove own app on mobile AppsList

CHANGELOG.md, package.json
=> chore: upgrade version

CHANGELOG.md, src/components/Bar.jsx, src/components/Settings.jsx, src/locales/en.json, src/styles/bar.css
This reverts commit e0061a1a6fa0c585c09869121fceeec239585383.
=> Revert "Revert "fix: remove beta status :sparkles:""

src/components/Settings.jsx, src/lib/reducers/apps.js, src/lib/stack.js
The coming soon apps was removed, get them back.
Add link to storage menu item to settings storage view.
=> Minor improvements

src/components/AppIcon.jsx, src/components/AppIconGroup.jsx, src/components/AppsList.jsx, src/components/Bar.jsx, src/components/ComingSoonModal.jsx, src/components/Drawer.jsx, src/components/FakeAppsList.jsx, src/components/Nav.jsx, src/components/PermsModal.jsx, src/components/Settings.jsx, src/locales/en.json, src/styles/navigation_item.css, src/styles/navigation_section.css
I put @y-lohse and @goldoraf for the last commit only. I don't have the context about the `FakeList` and the `PermsModal` so I prefer to be careful and be sure to not break anything on your side.
=> Add store description modal

src/components/SearchBar.jsx, src/styles/searchbar.css
This PR:
- removes a disturbing flash of content when typing or ESCaping ;
- put the suggestions' subtitles (file paths for instance) under the title ;
- fixes the top margin of the empty suggestion list.
=> Search UI minor enhancements

package.json, src/components/Bar.jsx, yarn.lock
=> fix: add object.assign polyfill

src/components/Bar.jsx
This PR aims to enable the search bar.
=> feat: enable searchbar

src/styles/bar.css, src/styles/searchbar.css
Minor style updates to the search bar — alignment and border styling.
=> Search styling

src/components/SearchBar.jsx, src/styles/searchbar.css
I explained the problem in details [here](https://trello.com/c/ZAiViH5Y/853-lors-de-la-premi%C3%A8re-requ%C3%AAte-de-recherche-les-r%C3%A9sultats-sont-incorrects#comment-5aa81310594b82416fea6ecc).
The call to `cancel` seems like the correct thing to do.
I included 2 other commits that fix minor issues.
=> Debounce 3

package.json, src/components/Banner.jsx, src/components/Bar.jsx, src/components/SupportModal.jsx, src/index.jsx, src/locales/en.json, src/styles/banner.css, src/styles/bar.css, src/styles/index.styl, src/styles/navigation_section.css, src/styles/supportModal.css, test/__mocks__/fileMock.js, test/__snapshots__/index.spec.js.snap, yarn.lock
~~⚠️ Waiting for next release of cozy-ui for a fix with `<ButtonLink />`~~
=> Add new banner for CGU update

package.json, src/components/Drawer.jsx, src/styles/drawer.css
Not much to add, besides the fact that the `overflow-y : scroll` bug on Chrome made things more... interesting ;)
=> Added RTL swipe to close the drawer

src/components/Drawer.jsx, src/styles/drawer.css
In this PR, I lowered the distance to swipe before the drawer close, and replaced the scale transform by a translate one.
=> Fine-tuned drawer swipe

package.json, src/styles/banner.css, src/styles/navigation_section.css, yarn.lock
=> fix: minor fixes

.travis.yml, package.json
- Deploy cozy-bar on npm with semantic-release
- Store encrypted tokens in travis.yml
=> chore: introducing semantic-release

package.json
Just tired of having bad shasum in my pull requests
=> Build before shasum

src/components/AppIconGroup.jsx, src/components/Bar.jsx, src/components/Claudy.jsx, src/components/Nav.jsx, src/components/SearchBar.jsx, src/components/Settings.jsx, src/styles/navigation_section.css, yarn.lock
=> feat: better code for better a11y

src/components/Apps/AppNavButtons.jsx
Issue remaining from last PR with the new navigation feature
=> Fix issue when homeApp not defined

src/components/Apps/AppsContent.jsx, src/styles/apps.css, src/styles/drawer.css, src/styles/nav.css
* Do not display home link when we are in the home application
* Better icons margin for settings and home buttons
* Better apps list margin
Thanks @kosssi for your feedback 👍
=> Minor UI fixes

src/components/Drawer.jsx, src/lib/BarStore.js
=> fix: Reset BarStore on logout

src/styles/apps.css, src/styles/drawer.css
* Horizontal scroll issue in drawer
* Add height limit to apps pop menu
=> Minor navigation UI fixes

src/components/Apps/AppsContent.jsx, src/styles/apps.css, src/styles/drawer.css, src/styles/nav.css, src/styles/navigation_item.css
* App item highlighting
* Pop menu position
* Home button change for mobile (see below)
=> Apps list UI fixes

src/styles/apps.css
A scroll was present on every menu item
=> Fix menu item scroll

package.json, yarn.lock
=> Upgrade cozy-ui for AppIcon fix

src/components/Apps/AppItem.jsx, src/components/Apps/AppNavButtons.jsx, src/components/Apps/AppsContent.jsx, src/lib/reducers/apps.js, src/styles/navigation_item.css, test/store/__snapshots__/index.spec.js.snap
* Apps was mapped after a process (set home application)
* Hover style was not correct on mobile drawer
* Don't replace home name
* Force home icon
=> Last fixes

src/components/Apps/AppItemPlaceholder.jsx, src/styles/apps.css, src/styles/navigation_item.css
This PR removes the hover effects on apps loading placeholders
It fixes element widths as well.
=> Better apps placeholders

src/styles/apps.css, src/styles/navigation_item.css
Remove blue left border for the home button on hover
=> Fix home btn hover style issue

src/components/Apps/AppNavButtons.jsx, src/components/Apps/index.jsx, src/components/Bar.jsx, src/index.jsx, src/lib/api.js, src/lib/middlewares/appsI18n.js, src/lib/store/index.js
This PR adds a middleware to automaticly add locales from app manifests into locales dictionary
=> WIP: Translate app name

src/components/Apps/AppItem.jsx, src/components/Bar.jsx, src/lib/middlewares/appsI18n.js, test/components/AppItem.spec.jsx, test/components/__snapshots__/AppItem.spec.jsx.snap
SET_LANG is the action to be dispatched by Settings when language changing
=> Fix locales handling

src/components/Apps/AppNavButtons.jsx, src/components/Apps/AppsContent.jsx, src/components/Bar.jsx, src/lib/reducers/apps.js, src/styles/apps.css, test/store/index.spec.js
=> Better apps fetching status

src/lib/reducers/apps.js, src/lib/stack.js
Equivalent of https://github.com/cozy/cozy-bar/pull/312 for version `5.0.8`.
=> Fix SVG icons on Cordova and iOS10

src/components/Bar.jsx, src/index.jsx, test/__snapshots__/index.spec.js.snap, test/index.spec.js
This feature is not use on Cozy Banks and Cozy Drive.
=> feat: Remove unnecessary feature

src/lib/reducers/apps.js
After talk with @Claiw on the last meeting, the current app should be display on mobile app like web.
=> feat: Display current app on mobile

src/components/Apps/AppsContent.jsx
=> fix: Polyglot display error when default value is undefined

src/components/Apps/AppsContent.jsx, src/components/Bar.jsx, src/styles/drawer.css
=> Fix ios showing the app rows over each other

src/index.jsx
Make these parts more readable and simple
=> More readeable api proxy parts

src/styles/navigation_item.css
Remove blue border for hover/focus on app items. The blue border is only for the current application.
=> Remove blue border left on apps focus/hover

src/components/Bar.jsx, src/lib/api/index.js, src/lib/reducers/content.js, src/lib/reducers/index.js, test/lib/__snapshots__/api.spec.js.snap, test/lib/api.spec.js
Use a list instead of a single value to handle API previous contents
=> Improve history handling for api store

src/lib/store/index.js
=> Prefix cozy bar actions for the logger

src/index.jsx
Avoid error about getting dataset of null
=> Better app node checking on init

src/lib/store/index.js
Allow offline usage with the apps list
=> Add apps reducer to redux-persist config

config/webpack.config.jsx.js, package.json, src/components/Apps/AppItem.jsx, src/lib/stack.js, test/components/__snapshots__/AppItem.spec.jsx.snap, test/jestLib/setup.js, yarn.lock
* Upgrade to cozy-ui v17
* Use props for `<AppIcon />`
=> Better app icons

src/components/Apps/AppNavButtons.jsx, src/styles/apps.css
* Do not display the app name prefix if this is the platform home application
* Use the correct blue color on visited home button
* Disable home button on public pages
=> Minor fixes

src/components/Apps/AppNavButtons.jsx, src/lib/store/index.js
* Disable correctly the link on public page
* Persist context to avoid getting a persisted home app without context and home information
=> Home application fix

src/lib/stack.js, test/components/__snapshots__/AppItem.spec.jsx.snap
Use two separate global variables for the host and the ssl usage
=> Icon props usage with SSL and HOST

src/lib/icon.js, src/lib/stack.js, src/styles/apps.css, test/components/AppItem.spec.jsx, test/components/__snapshots__/AppItem.spec.jsx.snap
* Use fetchIcon prop for AppIcon if mobile target
* Fix an offset of the home icon in the drawer
* Add tests for AppIcon on mobile
=> Better app icon handling on mobile

src/index.jsx
Disappeared from a last API change
=> Get back setLocale exposed

package.json, src/styles/bar.css
Je rapatrie le style de la cozy-bar qui est encore dans cozy-ui, voir la suppression dans la PR suivante https://github.com/cozy/cozy-ui/pull/832
=> feat: Add style on mobile device

src/components/Apps/AppItem.jsx, test/components/AppItem.spec.jsx
=> Use timeout drawer closing on app switch

src/config/persistWhitelist.yaml, src/lib/store/index.js
Better than using an hardcoded list
=> Use a config file for redux-persist whitelist

src/components/Apps/AppItem.jsx, src/index.jsx, src/lib/api/index.js, src/lib/intents.js, src/lib/middlewares/appsI18n.js, src/lib/reducers/apps.js, src/lib/reducers/context.js, src/lib/reducers/index.js, src/lib/stack-client.js, src/lib/stack-internal.js, src/lib/store/index.js
They avoid to use webpack alias on those imports
=> Remove remaining relative path imports

src/components/Bar.jsx, src/index.jsx, src/lib/realtime.js, src/lib/reducers/index.js, src/lib/stack-client.js, src/lib/stack-internal.js, src/lib/stack.js, src/styles/index.styl, test/components/AppItem.spec.jsx, test/components/Bar.spec.jsx, test/components/__snapshots__/AppItem.spec.jsx.snap, test/components/__snapshots__/Bar.spec.jsx.snap, test/lib/__snapshots__/stack.spec.js.snap, test/lib/stack-client/stack-client.init.spec.js, test/lib/stack.spec.js
Minor stack refactoring for better testing and code understanding
=> Minor revamp

src/config/excludedApps.yaml, src/lib/reducers/apps.js
Make excludes apps list setting up by a config file, will allow to customise this list
=> Make excludes apps list setting up by config file

package.json, yarn.lock
Was here but never used since cozy-bar uses `fetch()` directly
=> Remove unused cozy-client-js dep

src/components/Apps/AppsContent.jsx, src/lib/reducers/apps.js, yarn.lock
Allow to handle home application differently or not
=> Add parameter to include or not home app in apps list

package.json, src/components/Apps/AppItem.jsx, test/components/AppItem.spec.jsx, yarn.lock
The idea is to open from the "mobile web app" the native app if installed. If not, we redirect to the web version.
=> feat: Use deeplink for the web version of the bar

src/components/Apps/AppsContent.jsx, test/components/AppsContent.spec.jsx, test/components/__snapshots__/AppsContent.spec.jsx.snap
I had "can't read slug of undefined" because there is no parenthesis here: 
`app.slug !== homeApp && homeApp.slug` 
and if we add them, prettier remove them, so I just declared a const before ^^"
=> fix: Check correctly the slug

src/components/Apps/AppItem.jsx, src/config/native.js
With a dedicated file, it'll be easier to override native information for some context ;)
=> feat: Use an external file to get native app config

package.json, yarn.lock
to remove cozy-realtime 1.2.8 and used cozy-realtime 2.0.7
=> chore(harvest): Upgrade lib

src/index.jsx, src/lib/stack-client.js, src/lib/stack-internal.js, src/lib/stack-internal.spec.js, src/lib/stack.js, test/lib/stack-client/stack-client.init.spec.js
It's a try to fix #506 . I don't know if this is the way to go? Any ideas ?
=>  fix: Don't subscribe to realtime if is public

package.json, yarn.lock
Necessary to have the `fetch` function used in <Query /> (used in overrides to refetch konnectors/triggers when app resumes).
=> chore: Update cozy-client

src/styles/bar.css
Fixes the MQ setting the bar on position fixed.
It was at 1024px when it should have been 1023px so the bar was misplaced at exactly 1024px on every apps.
=> fix: MQ for tablets

src/components/SearchBar.jsx
In fact there is a lot of message sent during dev process : 
- React dev tools
- Redux dev tools 
- ...
=> feat: Use minilog to log unhandled message

package.json, yarn.lock
=> Revert "fix(deps): update dependency @babel/core to v7.4.5"

package.json, test/lib/stack-client/stack-client.appiconprops.spec.js, test/lib/stack-client/stack-client.cozyfetchjson.spec.js, test/lib/stack-client/stack-client.cozyurl.spec.js, test/lib/stack-client/stack-client.getapp.spec.js, test/lib/stack-client/stack-client.getapps.spec.js, test/lib/stack-client/stack-client.getcontext.spec.js, test/lib/stack-client/stack-client.getstoragedata.spec.js, test/lib/stack-client/stack-client.init.spec.js, test/lib/stack-client/stack-client.logout.spec.js
Test folder was not included in the linting rules.
=> chore: Lint tests

package.json, yarn.lock
Harvest should be a peerDep as all the other cozy-* ;)
=> fix(dep): Harvest is a peerDep and dev Dep

src/lib/importIcons.js
before:  ./dist/cozy-bar.min.js: 288.76KB
after:  /dist/cozy-bar.min.js: 256.01KB < maxSize 300KB (gzip)
=> fix: Do not require dynamic

.travis.yml
It ssems that the previous token is not working anymore
=> fix: Bundlesize token

config/webpack.js, package.json, src/components/Settings/SettingsContent.jsx, src/index.jsx, src/lib/stack-client.js, test/components/AppItem.spec.jsx, test/components/__snapshots__/AppItem.spec.jsx.snap, test/lib/stack-client/stack-client.appiconprops.spec.js, yarn.lock
We need the bar to be as standalone as possible. First step remove reference to webpack var. 
Need https://github.com/cozy/cozy-ui/pull/1105
=> fix: Remove reference to __TARGET__

src/lib/middlewares/appsI18n.js
Those logs do not provide a way to fix the problem and are appearing every
time.
=> feat: Logs appearing every time and not really helpful

src/lib/realtime.js
Realtime: options.cozyClient is deprecated, please use options.client
=> fix: Remove warning

src/components/Claudy.jsx
Remove a warning in the console
=> fix: Use UNSAFE for componentWillReceiveProps

src/components/Settings/SettingsContent.jsx, src/components/Settings/index.jsx, src/locales/en.json
the idea: 
- If we haven't an offer : We display "View offers"
- If we already have an offer, then we display "My offer"
=> feat: Display My offer if needed

src/index.jsx, src/index.spec.jsx
Oups. I had replaced the exposedAPI variable which resulted in
not being to use the API (BarCenter, BarLeft etc...) in apps.
=> fix: Need to assign methods to API instead of replacing the var

.travis.yml, package.json, src/components/Drawer.jsx, src/components/Drawer.spec.jsx, yarn.lock
Otherwise we risk to not completely cleanup the local pouch
=> fix: Await onLogOut callback

src/index.jsx
Otherwise we have an errors "exports" is read-only
=> fix: Do not use module.exports and imports in the same file

src/components/Bar.jsx, src/components/__snapshots__/Bar.spec.jsx.snap, src/index.jsx, src/lib/api/helpers.js, src/lib/api/index.jsx, src/lib/reducers/content.js, test/lib/__snapshots__/api.spec.jsx.snap, test/lib/api.spec.jsx
With this, we will be able to show a custom search bar in the bar.
Should Drive use this capacity to show its search bar (this way the bar would not carry the code that is at the moment very specific to drive) ?
=> feat: Ability to show something in the search part of the bar

README.md
=> docs: Add some info to use the bar with Context

package.json, yarn.lock
The old minilog github link seems to break the CI build
=> fix: Replace minilog with @cozy/minilog

src/components/Apps/AppNavButtons.jsx, src/components/Apps/ButtonCozyHome.spec.jsx
=> fix: Remove relative import

package.json, src/components/Apps/ButtonCozyHome.jsx, src/components/Apps/ButtonCozyHome.spec.jsx, src/styles/apps.css
Button is causing trouble on Safari since it displays
a button...
Let's use an A like we do in all other places.
=> fix: Use A instead of button

package.json, src/components/Apps/ButtonCozyHome.jsx, src/components/Bar.jsx, src/lib/logger.js, src/styles/apps.css, yarn.lock
Adds convenience for debugging purposes
=> feat: Allow cozy-flag to display home button

package.json, src/styles/settings.css
Bug doesn't seem to appear on v8
=> fix: Vertical align settings button content

README.md, package.json
This will make developing in v7 easier
=> feat: Add a readme section for dev

src/components/Bar.jsx, src/components/SearchBar.jsx, src/components/__snapshots__/Bar.spec.jsx.snap
you have to use client coming from prop because with hoc or hooks
it might cause this Minified React Error
=> fix(Search): withClient provoked Minified React Error

babel.config.js, config/webpack.config.base.js, src/components/Bar.jsx, src/components/Bar.spec.jsx
=> feat: Remove Matomo V8

src/styles/base.css, src/styles/nav.css, src/styles/settings.css
```
* Update dropdown spacing to fit with UI specifications
```
=> fix: Update dropdown spacing to fit with UI specifications

package.json, src/index.jsx, yarn.lock
```
### Tech
* WebviewIntentProvider is already added in apps using the bar.
```
=> fix: Remove duplicate WebviewIntentProvider

src/components/Settings/SettingsContent.jsx, src/styles/base.css, src/styles/settings.css
```
* Make hover and focus of dropdown item fullsize again
```
=> fix: Make hover and focus of dropdown item fullsize again

src/styles/supportModal.css
Adapted the height to match the change in the support form which increased with the consent checkbox
=> Fix : support modal height

src/styles/supportModal.css
Adapted the height to match the change in the support form which increased with the consent checkbox
=> fix: Increase height for support modal

src/lib/reducers/apps.js, src/lib/reducers/apps.spec.js, src/locales/en.json, src/locales/fr.json, src/styles/apps.css, test/components/__snapshots__/AppsContent.spec.jsx.snap
fix: Increase app list height to see 8.5 apps
fix: Rename "back to home" link to "back to dashboard"
fix: Set default app always to home
fix: Cloud icon was too close to home text button
=> Increase app list height and set default app always to home (V8)

README.md, src/components/Apps/AppItem.jsx, src/components/Apps/AppNavButtons.jsx, src/components/Apps/AppsContent.jsx, src/components/Apps/ButtonCozyHome.jsx, src/components/Apps/IconCozyHome.jsx, src/components/Apps/index.jsx, src/components/Bar.jsx, src/components/Drawer.jsx, src/index.jsx
Same as https://github.com/cozy/cozy-bar/pull/825
=> feat: Add isInvertedTheme param

src/components/Settings/index.jsx, src/locales/fr.json
Will redirect to store if settings.subscription flag is present
=> feat: update managerUrlPremiumLink if sub (VO-386)

src/components/Bar.jsx, src/components/Settings/index.jsx, src/components/__snapshots__/Bar.spec.jsx.snap, src/locales/fr.json
Will redirect to store if settings.subscription flag is present
=> feat: update link for subscription flag (VO-386)

src/components/Settings/SettingsContent.jsx, src/components/Settings/index.jsx
subscription flag is singular
also don't display externalIcon if flag is true
=> fix: Update subscription flag management (VO-386)

src/components/Settings/SettingsContent.jsx
Hide openwith if has subscription
=> Fix--Update-subscription-flag-management(v7) (VO-386)

src/components/Settings/SettingsContent.jsx, src/locales/en.json, src/locales/fr.json, src/styles/bar.css
`ui.darkmode.enabled` must be enabled
=> feat: Add menu entry to go to appearance settings page

README.md, package.json, src/components/Bar.jsx, src/components/BarComponent.jsx, src/components/BarRoutes.jsx, src/index.jsx, yarn.lock
Goal : allow every app to enable to search and AI assistant in one line !
See the README commit to understand how it work in this proposition 5a7596f5500eb5daa4fe46ec9b4814108c393b7f
---
To do : 
---
In cozy-drive : https://github.com/cozy/cozy-drive/pull/3329
In libs : https://github.com/cozy/cozy-libs/pull/2748
=> Move search in bar

package.json, src/components/Apps/ButtonCozyHome.jsx, src/components/Apps/IconCozyHome.jsx, src/components/AppsMenu/AppsMenuContent.jsx, src/components/AppsMenu/components/AppItem.jsx, src/components/AppsMenu/index.jsx, src/components/Bar.jsx, src/components/UserMenu/UserMenuContent.jsx, src/components/UserMenu/components/AvatarMyself.jsx, src/components/UserMenu/helpers.js, src/components/UserMenu/index.jsx, src/styles/apps-menu.styl, src/styles/user-menu.styl, yarn.lock
Following https://github.com/cozy/cozy-bar/pull/864
=> Clean new bar code

package.json, yarn.lock
BREAKING CHANGE: You now need `cozy-ui >= 122.0.1`
=> feat: Update cozy-search
